//Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
//By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million,
//find the sum of the even-valued terms.

#include <iostream>
using namespace std;

int main(){

    int i=3,n1=1,n2=2,fib=0,sumaPares=2;
    while (i<10){

        fib=n1+n2;

        if(fib%2==0){
            sumaPares+=fib;
        }

        n1=n2;
        n2=fib;
        i++;
    }
    
    cout<<"La suma de los 10 primeros terminos pares de Fibonacci es: "<<sumaPares<<endl;

    i=3;n1=1;n2=2;fib=0;sumaPares=2;
    while (fib<4000000){

        fib=n1+n2;
        
        if(fib%2==0){
            sumaPares+=fib;
        }

        n1=n2;
        n2=fib;
        i++;

        
    }
    
    cout<<"La suma de los valores pares que no exceden de 400000 de Fibonacci es: "<<sumaPares<<endl;
    

}




